import mongoose from 'mongoose'

const journalLineSchema = new mongoose.Schema({
  accountCode: { type: String, required: true },
  accountName: String,
  debitFormula: String, // e.g., 'sourceDoc.subTotal', 'sourceDoc.totalCGST'
  creditFormula: String,
  description: String
})

const ledgerActivityMappingSchema = new mongoose.Schema({
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  mappingCode: {
    type: String,
    required: true,
    trim: true
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  module: {
    type: String,
    enum: ['accounts_payable', 'accounts_receivable', 'payments', 'payroll', 'inventory', 'bank', 'gst', 'tds'],
    required: true
  },
  triggerEvent: {
    type: String,
    enum: [
      'vendor_invoice_approved', 'vendor_invoice_cancelled',
      'customer_invoice_created', 'customer_invoice_cancelled',
      'payment_outgoing_completed', 'payment_incoming_completed',
      'payroll_processed',
      'material_consumed', 'material_received',
      'tds_deduction', 'gst_adjustment',
      'advance_payment_vendor', 'advance_receipt_customer',
      'credit_note_issued', 'debit_note_issued'
    ],
    required: true
  },
  journalTemplate: [journalLineSchema],
  isActive: {
    type: Boolean,
    default: true
  },
  isSystem: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, { timestamps: true })

ledgerActivityMappingSchema.index({ company: 1, mappingCode: 1 }, { unique: true })
ledgerActivityMappingSchema.index({ company: 1, triggerEvent: 1 })
ledgerActivityMappingSchema.index({ company: 1, module: 1 })

// Static method: Execute a mapping to auto-create journal entry
ledgerActivityMappingSchema.statics.executeMapping = async function(companyId, triggerEvent, sourceDoc, userId) {
  const mapping = await this.findOne({
    company: companyId,
    triggerEvent,
    isActive: true
  })

  if (!mapping) return null

  const ChartOfAccounts = mongoose.model('ChartOfAccounts')
  const JournalEntry = mongoose.model('JournalEntry')

  // Resolve formula values from source document
  const resolveFormula = (formula) => {
    if (!formula) return 0
    try {
      // Simple dot-notation resolver
      const parts = formula.split('.')
      let value = sourceDoc
      for (const part of parts) {
        if (part === 'sourceDoc') continue
        value = value?.[part]
      }
      return parseFloat(value) || 0
    } catch {
      return 0
    }
  }

  const lines = []
  for (const tmpl of mapping.journalTemplate) {
    const debitAmount = resolveFormula(tmpl.debitFormula)
    const creditAmount = resolveFormula(tmpl.creditFormula)
    if (debitAmount === 0 && creditAmount === 0) continue

    const account = await ChartOfAccounts.findOne({
      company: companyId,
      accountCode: tmpl.accountCode,
      isActive: true
    })

    if (account) {
      lines.push({
        account: account._id,
        accountCode: tmpl.accountCode,
        accountName: account.accountName,
        debit: debitAmount,
        credit: creditAmount,
        description: tmpl.description || mapping.name
      })
    }
  }

  if (lines.length === 0) return null

  // Create auto journal entry
  const journalEntry = await JournalEntry.create({
    company: companyId,
    entryNumber: `AUTO-${Date.now()}`,
    entryDate: new Date(),
    entryType: 'standard',
    description: `Auto: ${mapping.name}`,
    lines,
    sourceModule: mapping.module,
    sourceDocument: sourceDoc._id,
    isAutoGenerated: true,
    status: 'posted',
    createdBy: userId,
    postedBy: userId,
    postedAt: new Date()
  })

  // Update account balances
  for (const line of lines) {
    const account = await ChartOfAccounts.findOne({
      company: companyId,
      accountCode: line.accountCode
    })
    if (account) {
      await account.updateBalance(line.debit, line.credit)
    }
  }

  return journalEntry
}

const LedgerActivityMapping = mongoose.model('LedgerActivityMapping', ledgerActivityMappingSchema)
export default LedgerActivityMapping
